version: '3.9' 
 
services: 
 postgres: 
   image: postgres:15 
   container_name: dbt_postgres 
   restart: always 
   environment: 
     POSTGRES_USER: sherwin
     POSTGRES_PASSWORD: Sherwin@1234
     POSTGRES_DB: test
   ports: 
     - "5432:5432" 
   volumes: 
     - postgres_data:/var/lib/postgresql/data 
   networks: 
     - dbt_network 
 
 dbt: 
   build: . 
   container_name: dbt_core 
   environment:
      # This path must match where the .dbt folder is inside the container
    - DBT_PROFILES_DIR=/usr/app/dbt_project/.dbt
   tty: true
   stdin_open: true
   volumes: 
    - .:/usr/app        # add this
   depends_on: 
     - postgres 
   networks: 
     - dbt_network 
 
volumes: 
 postgres_data: 
 
networks: 
 dbt_network: 
   driver: bridge 